//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;
use sea_skipper::DeriveNewModel;
use serde::{Deserialize, Serialize};

// `DeriveNewModel` derives a `NewModel` type similar to `Model` but without the primary key `id` field.
// This may be used for create requests defining a new cake that hasn't been inserted into the
// database yet.
#[derive(
    Clone, Debug, PartialEq, Eq, DeriveEntityModel, DeriveNewModel, Serialize, Deserialize,
)]
#[sea_orm(table_name = "cake")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
