name: Format

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.rs'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.rs'

env:
  CARGO_TERM_COLOR: always

jobs:
  Formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: cargo fmt -- --check -v
