name: Lint

on:
  push:
    branches: [ "main" ]
    paths:
      - '**/Cargo.*'
      - '**.rs'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**/Cargo.*'
      - '**.rs'

env:
  CARGO_TERM_COLOR: always

jobs: 
 Lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: cargo clippy
